// Admin
export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILED = "ADMIN_LOGIN_FAILED";
export const GET_TEACHERS = "GET_TEACHERS"
export const GET_TEACHER = 'GET_TEACHER'
export const GET_STUDENTS="GET_STUDENTS"
export const TOGGLE_TRUE='TOGGLE_TRUE'
export const TOGGLE_FALSE='TOGGLE_FALSE'
export const GET_COURSES = 'GET_COURSES'
export const GET_COURSE = 'GET_COURSE'

export const GET_PROFIL = "GET_PROFIL";
export const GET_PROFIL_SUCCESS = "GET_PROFIL_SUCCESS";
export const GET_PROFIL_FAILED = "GET_PROFIL_FAILED";

// Student

export const STUDENT_REGISTER = "STUDENT_REGISTER";
export const STUDENT_REGISTER_SUCCESS = "STUDENT_REGISTER_SUCCESS";
export const STUDENT_REGISTER_FAILED = "STUDENT_REGISTER_FAILED";
